export const ErrorCode = {
  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_MERGE_REQUIRED_EMAIL: 'AUTH_MERGE_REQUIRED_EMAIL',
  AUTH_MERGE_REQUIRED_GOOGLE: 'AUTH_MERGE_REQUIRED_GOOGLE',
  AUTH_NO_ACCOUNT_FOUND: 'AUTH_NO_ACCOUNT_FOUND',
  AUTH_ACCOUNT_EXISTS_GOOGLE: 'AUTH_ACCOUNT_EXISTS_GOOGLE',
  AUTH_ACCOUNT_EXISTS_EMAIL: 'AUTH_ACCOUNT_EXISTS_EMAIL',
  AUTH_ACCOUNT_CONFIG_ERROR: 'AUTH_ACCOUNT_CONFIG_ERROR',
  AUTH_INVALID_GOOGLE_TOKEN: 'AUTH_INVALID_GOOGLE_TOKEN',
  AUTH_PASSWORD_TOO_SHORT: 'AUTH_PASSWORD_TOO_SHORT',
  AUTH_PASSWORD_NO_UPPERCASE: 'AUTH_PASSWORD_NO_UPPERCASE',
  AUTH_PASSWORD_NO_NUMBER: 'AUTH_PASSWORD_NO_NUMBER',
  AUTH_PASSWORD_ALREADY_SET: 'AUTH_PASSWORD_ALREADY_SET',
  AUTH_TOKEN_REVOKED: 'AUTH_TOKEN_REVOKED',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_MISSING_TOKEN: 'AUTH_MISSING_TOKEN',
  AUTH_INVITATION_REQUIRED: 'AUTH_INVITATION_REQUIRED',
  AUTH_INVITATION_INVALID: 'AUTH_INVITATION_INVALID',
  AUTH_INVITATION_EMAIL_MISMATCH: 'AUTH_INVITATION_EMAIL_MISMATCH',

  // Store
  STORE_NOT_FOUND: 'STORE_NOT_FOUND',
  STORE_NO_ACCESS: 'STORE_NO_ACCESS',
  STORE_NO_STORE_SELECTED: 'STORE_NO_STORE_SELECTED',
  STORE_NAME_REQUIRED: 'STORE_NAME_REQUIRED',
  STORE_CREATE_INVITATION_REQUIRED: 'STORE_CREATE_INVITATION_REQUIRED',
  STORE_CREATE_INVITATION_INVALID: 'STORE_CREATE_INVITATION_INVALID',
  STORE_INVITE_INVALID: 'STORE_INVITE_INVALID',
  STORE_INVITE_WRONG_TYPE: 'STORE_INVITE_WRONG_TYPE',
  STORE_ONLY_OWNER_CAN_INVITE: 'STORE_ONLY_OWNER_CAN_INVITE',
  STORE_ONLY_OWNER_CAN_REVOKE: 'STORE_ONLY_OWNER_CAN_REVOKE',
  STORE_ONLY_OWNER_CAN_REMOVE: 'STORE_ONLY_OWNER_CAN_REMOVE',
  STORE_CANNOT_REMOVE_SELF: 'STORE_CANNOT_REMOVE_SELF',
  STORE_CANNOT_REMOVE_OWNER: 'STORE_CANNOT_REMOVE_OWNER',
  STORE_MEMBER_NOT_FOUND: 'STORE_MEMBER_NOT_FOUND',
  STORE_INVITE_ALREADY_REVOKED: 'STORE_INVITE_ALREADY_REVOKED',
  STORE_NO_ROLE: 'STORE_NO_ROLE',
  STORE_EMAIL_REQUIRED: 'STORE_EMAIL_REQUIRED',
  STORE_ADMIN_PRIVILEGES_REVOKED: 'STORE_ADMIN_PRIVILEGES_REVOKED',
  STORE_ADMIN_REQUIRED: 'STORE_ADMIN_REQUIRED',

  // Customer
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  CUSTOMER_CONFLICT: 'CUSTOMER_CONFLICT',
  CUSTOMER_HAS_OPEN_ORDERS: 'CUSTOMER_HAS_OPEN_ORDERS',

  // Order
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_NO_OCCURRENCES: 'ORDER_NO_OCCURRENCES',
  ORDER_CANNOT_DELETE_RECEIVED: 'ORDER_CANNOT_DELETE_RECEIVED',
  ORDER_INVALID_STATUS_TRANSITION: 'ORDER_INVALID_STATUS_TRANSITION',

  // Recipe
  RECIPE_NOT_FOUND: 'RECIPE_NOT_FOUND',
  RECIPE_IN_USE_BY_ORDERS: 'RECIPE_IN_USE_BY_ORDERS',
  RECIPE_CIRCULAR_REFERENCE: 'RECIPE_CIRCULAR_REFERENCE',

  // Inventory
  INGREDIENT_NOT_FOUND: 'INGREDIENT_NOT_FOUND',
  INGREDIENT_IN_USE_BY_RECIPES: 'INGREDIENT_IN_USE_BY_RECIPES',
  STOCK_ADJUSTMENT_POSITIVE: 'STOCK_ADJUSTMENT_POSITIVE',

  // Payment
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_ALREADY_REFUNDED: 'PAYMENT_ALREADY_REFUNDED',

  // Production
  BATCH_NOT_FOUND: 'BATCH_NOT_FOUND',
  BATCH_SPLIT_QUANTITY_TOO_HIGH: 'BATCH_SPLIT_QUANTITY_TOO_HIGH',
  BATCH_MERGE_MISMATCH: 'BATCH_MERGE_MISMATCH',
  PREP_ITEM_NOT_FOUND: 'PREP_ITEM_NOT_FOUND',

  // Loyalty
  LOYALTY_NOT_ACTIVE: 'LOYALTY_NOT_ACTIVE',
  LOYALTY_INSUFFICIENT_POINTS: 'LOYALTY_INSUFFICIENT_POINTS',
  LOYALTY_BELOW_MINIMUM: 'LOYALTY_BELOW_MINIMUM',
  LOYALTY_NEGATIVE_BALANCE: 'LOYALTY_NEGATIVE_BALANCE',

  // Settings — Allergens
  ALLERGEN_NOT_FOUND: 'ALLERGEN_NOT_FOUND',
  ALLERGEN_DEFAULT_IMMUTABLE: 'ALLERGEN_DEFAULT_IMMUTABLE',
  ALLERGEN_NOT_AUTHORIZED: 'ALLERGEN_NOT_AUTHORIZED',

  // Settings — Tags
  TAG_NOT_FOUND: 'TAG_NOT_FOUND',

  // Settings — Units
  UNIT_NOT_FOUND: 'UNIT_NOT_FOUND',
  UNIT_INVALID_CATEGORY: 'UNIT_INVALID_CATEGORY',
  UNIT_DEFAULT_IMMUTABLE: 'UNIT_DEFAULT_IMMUTABLE',
  UNIT_NOT_AUTHORIZED: 'UNIT_NOT_AUTHORIZED',

  // Settings — Notifications
  NOTIFICATION_SMS_NO_PHONE: 'NOTIFICATION_SMS_NO_PHONE',

  // Profile
  USER_NOT_FOUND: 'USER_NOT_FOUND',

  // Admin
  ADMIN_CANNOT_CHANGE_OWN_STATUS: 'ADMIN_CANNOT_CHANGE_OWN_STATUS',
  ADMIN_CANNOT_MODIFY_ADMIN: 'ADMIN_CANNOT_MODIFY_ADMIN',
  ADMIN_CANNOT_DISABLE_SELF: 'ADMIN_CANNOT_DISABLE_SELF',
  ADMIN_CANNOT_DISABLE_ADMIN: 'ADMIN_CANNOT_DISABLE_ADMIN',
  ADMIN_CANNOT_DELETE_SELF: 'ADMIN_CANNOT_DELETE_SELF',
  ADMIN_CANNOT_DELETE_ADMIN: 'ADMIN_CANNOT_DELETE_ADMIN',
  ADMIN_INVITE_NOT_FOUND: 'ADMIN_INVITE_NOT_FOUND',
  ADMIN_INVITE_USED: 'ADMIN_INVITE_USED',
  ADMIN_INVITE_ALREADY_REVOKED: 'ADMIN_INVITE_ALREADY_REVOKED',
  ADMIN_INVALID_STATUS_FILTER: 'ADMIN_INVALID_STATUS_FILTER',
  ADMIN_EMAIL_REQUIRED: 'ADMIN_EMAIL_REQUIRED',
  ADMIN_FIELD_REQUIRED: 'ADMIN_FIELD_REQUIRED',
  ADMIN_INVALID_CREDENTIALS: 'ADMIN_INVALID_CREDENTIALS',

  // Feature flags
  FEATURE_DISABLED: 'FEATURE_DISABLED',

  // Generic
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
